### ISSUE TITLE
Aviation Manjuu for airstrike calculator

### ISSUE THREAD

**Issue by Renhex** [Traneptora/traneptora.com#1]
Suggestion to add [Elite Aviation Maintenance Manjuu](https://azurlane.koumakan.jp/wiki/Elite_Aviation_Maintenance_Manjuu) to airstrike cd calc, works like a reverse beacon as far as cd is concerned so adding another checkbox for it would be nice

**Comment by Traneptora** [comment]
Makes sense, I just have to check how it stacks with beacon and the like. Once I figure out the math I can add it.

**Comment by Renhex** [comment]
looks good now
